project:
  type: default
  render:
    - main.qmd
    - README.qmd

title: "Mock R submission for Computo"
subtitle: "A simple illustration"
author:
  - name: Computoast
    corresponding: true
    email: computoast@proton.me
    url: https://computoast.themoon.org
    orcid: 0000-0000-0000-0000
    affiliations:
      - name: Computo Lab
        department: Statistics and ML
        url: https://computolabe.themoon.org
date: last-modified
date-modified: last-modified
abstract: >+
  Template for preparing a submission to Computo, using the [quarto journal extension](https://github.com/computorg/computo-quarto-extension), the knitr kernel (R user) and [renv](https://rstudio.github.io/renv/articles/renv.html) to set up the dependencies.
  
  For a detailed, step-by-step guide on preparing your article, setting up the continuous integration and submitting it to Computo, please consult the [guidelines for authors](https://computo-journal.org/site/guidelines-authors.html).
keywords: [key1, key2, key3]
bibliography: references.bib
github-user: computorg
repo: "template-computo-r"
status: "submitted"
citation:
  type: article-journal
  container-title: "Computo"
  issn: "2824-7795"
  doi: "10.5072/computo.0000" # placeholder DOI (10.5072 is the official DOI test prefix), replace once assigned
license: CC-BY-4.0
format:
  computo-html: default
  computo-pdf: default
